<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
title{
  font-family: Lobster, monospace;
}
</style>

theme: jekyll-theme-cayman
title: Test Website
description: This website is used for testing purposes. While coded in HTML currently, will be updated with more features soon.
